version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=NoHayMas
      - DB_NAME=uarp_ai
      - NODE_ENV=production
      # - SKIP_AUTH=true  # Solo para pruebas locales, eliminar o poner en false en producci√≥n
    depends_on:
      - postgres
      - ia-panel
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
      - NODE_ENV=production
    depends_on:
      - backend
  ia-panel:
    build: ./ia
    ports:
      - "5001:5001"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: uarp_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NoHayMas
    # ports:
    #   - "5432:5432"  # Solo exponer en desarrollo local si es necesario
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
